# Generated by Django 4.1.2 on 2023-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=1),
        ),
    ]
